/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.barclays.masterjson;

import org.junit.Test;
import com.barclays.masterjson.Main;

import static org.junit.Assert.*;

public class MainTest {
    @Test public void testSomeLibraryMethod() {
        Main classUnderTest = new Main();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
